### ISSUE TITLE
Метод «add» класса «CreditAccount» не учитывает начальный баланс при пополнении счета

### ISSUE THREAD

**Issue by NastiaUzdemir** [NastiaUzdemir/teamdip#2]
# Описание
При пополнении счета на сумму больше нуля, не учитывается начальное состояние баланса, рассчитывается только сумма, которая кладётся на счет методом «add» класса «CreditAccount» .

# Локация дефекта
https://github.com/NastiaUzdemir/teamdip/blob/7681183ddf6f1bf616f672dc7675f4a188555683/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/NastiaUzdemir/teamdip/blob/7681183ddf6f1bf616f672dc7675f4a188555683/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69) в IDEA.
2. Создать объект класса CreditAccount с начальным балансом 1_000.
3. Пополнить счет на 3_000.
4. Запустить программу.
5. Посмотреть на вывод в консоли.

* Ожидаемый результат: итоговый баланс 4_000.
* Фактический результат: итоговый баланс 3_000.

# Тест
https://github.com/NastiaUzdemir/teamdip/blob/5f0df3a3fc7d939d35d717c8d8fdc86500b57504/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L23-L34

# Окружение
* **Операционная система:** MacOS Sonoma 14.2.1
* **IDE:** IntelliJ IDEA 2023.3.1 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by MilenaTabakova** [comment]
bug fixed
