### ISSUE TITLE
Баланс становится отрицательным при оплате покупки в методе «pay» класса «CreditAccount» 

### ISSUE THREAD

**Issue by NastiaUzdemir** [NastiaUzdemir/teamdip#5]
# Описание
Баланс счета не обновляется в соответствии с оплаченной суммой в методе «pay» класса «CreditAccount», а становится равным отрицательному значению.

# Локация дефекта
https://github.com/NastiaUzdemir/teamdip/blob/5f0df3a3fc7d939d35d717c8d8fdc86500b57504/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/NastiaUzdemir/teamdip/blob/5f0df3a3fc7d939d35d717c8d8fdc86500b57504/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46) в IDEA.
2. Создать объект класса CreditAccount с начальным балансом 1_000.
3. Создать объект класса CreditAccount с кредитным лимитом 5_000.
4. Создать объект класса CreditAccount со ставкой 10.
5. Вызвать метод pay() и передать сумму оплаты в размере 500
6. Запустить программу.
7. Посмотреть на вывод в консоли.

* Ожидаемый результат: 500
* Фактический результат: -500

# Тест
https://github.com/NastiaUzdemir/teamdip/blob/5f0df3a3fc7d939d35d717c8d8fdc86500b57504/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L92-L103

# Окружение
* **Операционная система:** MacOS Sonoma 14.2.1
* **IDE:** IntelliJ IDEA 2023.3.1 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by MilenaTabakova** [comment]
bug fixed
